### ISSUE TITLE
Bot should assign FormatCheckRequested when there is no name given

### ISSUE THREAD

**Issue by okkhoy** [mauris/cs2103-pr-bot#2]
E.g. [T6A1][W11-C4] #595
Link to PR: https://github.com/nus-cs2103-AY1617S1/addressbook-level3/pull/595

**Comment by yamgent** [comment]
Just a heads up, the instructions for T6A1 specifies that no name should be provided:

> Submission: This is a team submission. Create a PR from the `master` branch your team repo to `nus-cs2103-AY1617S1/addressbook-level3`. PR name is similar to previous tutorial activities, but omit the student name. e.g. `[T6A2][T11-B3]`

**Comment by okkhoy** [comment]
Ah! great! I missed that! Sorry. Will close the issue :-)
